name: Update Velog Posts

on:
  push:
      branches:
        - main
  schedule:
    - cron: '0 12 * * *' # UTC 12:00 (KST 21:00)

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        git config --global user.name 'Queue-ri'
        git config --global user.email 'qriositylog@gmail.com'
        git push https://${{ secrets.VELOG_CI_PAT }}@github.com/Queue-ri/velog.git

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py
